import { headers } from "next/headers";
import { Chatbot } from "@/components/common/Chatbot";
import { ContentPage } from "@/components/common/ContentPage";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { getSiteConfig } from "@/config/siteConfig";

export default async function TermsPage() {
  const site = getSiteConfig((await headers()).get("host") ?? "");
  return <div className={`site-shell site-${site.key}`} style={{ "--brand-primary": site.primaryColor, "--brand-secondary": site.secondaryColor, "--brand-accent": site.accentColor } as React.CSSProperties}><Header site={site} /><main><ContentPage site={site} eyebrow="Terms of use" title="Clear terms for using the service." intro={`Last updated: September 8, 2026. These terms describe the agreement between you and ${site.siteName} when you use our website and services.`} sections={[{ title: "Using the service", paragraphs: ["You may use the service only for lawful purposes and in accordance with these terms. You are responsible for the information you submit and for keeping your account details secure."] }, { title: "General information only", paragraphs: [`Content provided through ${site.siteName} is general information and a starting point for research. It is not legal, financial, medical, tax, or other professional advice, and it does not create a professional relationship. Consider your circumstances and consult a qualified professional when appropriate.`] }, { title: "Questions and responses", paragraphs: ["We aim to provide useful, clear information, but we do not promise that every response will be complete, current, accurate, or suitable for your situation. Do not rely on the service for emergencies or urgent decisions."] }, { title: "Payments, cancellations, and refunds", paragraphs: ["If a paid feature is offered, the price and material terms will be shown before you complete the purchase. Any available cancellation or refund terms will be presented at checkout or in the applicable service description. Contact support promptly if you believe a charge is incorrect."] }, { title: "Prohibited activity", paragraphs: ["Do not misuse the service, interfere with its operation, attempt unauthorized access, submit malicious code, impersonate another person, or use content to violate another person’s rights or applicable law."] }, { title: "Content and availability", paragraphs: ["You retain rights to content you submit. You give us permission to process it as needed to operate, secure, and improve the service. Features may change, be suspended, or become unavailable as we maintain and develop the service."] }, { title: "Disclaimers and liability", paragraphs: ["To the extent permitted by law, the service is provided on an as-is and as-available basis. We are not responsible for decisions made from general information or for indirect losses resulting from use of the service. Nothing in these terms limits rights that cannot legally be limited."] }, { title: "Changes and contact", paragraphs: ["We may update these terms by posting a revised version on this page. Your continued use after an update means you accept the revised terms. Questions can be sent through our contact page."] }]} /></main><Footer site={site} /><Chatbot /></div>;
}