import { headers } from "next/headers";
import { Chatbot } from "@/components/common/Chatbot";
import { ContentPage } from "@/components/common/ContentPage";
import { Footer } from "@/components/layout/Footer";
import { Header } from "@/components/layout/Header";
import { getSiteConfig } from "@/config/siteConfig";

export default async function PrivacyPage() {
  const site = getSiteConfig((await headers()).get("host") ?? "");
  return <div className={`site-shell site-${site.key}`} style={{ "--brand-primary": site.primaryColor, "--brand-secondary": site.secondaryColor, "--brand-accent": site.accentColor } as React.CSSProperties}><Header site={site} /><main><ContentPage site={site} eyebrow="Privacy policy" title="How we handle information." intro={`Last updated: September 8, 2026. This policy explains how ${site.siteName} collects, uses, and protects information when you use our website and services.`} sections={[{ title: "Information you provide", paragraphs: ["We may collect information you choose to provide, such as a question, contact details, account information, and messages sent to support. Please do not submit passwords, payment card numbers, or sensitive information unless a form specifically requests it."] }, { title: "Information collected automatically", paragraphs: ["We may receive basic technical information such as your browser type, device information, approximate location, pages viewed, and interaction data. Cookies or similar technologies may help us keep the service secure, understand usage, and improve the experience."] }, { title: "How we use information", paragraphs: ["We use information to provide and maintain the service, respond to support requests, prevent misuse, communicate important service updates, process transactions when applicable, and improve our content and features."] }, { title: "Sharing and service providers", paragraphs: ["We may share information with vendors that help us operate the website, hosting, analytics, communications, payments, and security. These providers may use information only to perform services for us. We do not sell personal information for money."] }, { title: "Your choices and rights", paragraphs: ["You may contact us to ask about, correct, or delete personal information, subject to applicable law and legitimate operational needs. You can also manage cookies through your browser settings. We will verify requests when reasonably necessary to protect accounts and personal information."] }, { title: "Retention and security", paragraphs: ["We retain information only as long as reasonably necessary for the purposes described here, legal obligations, dispute resolution, and security. We use administrative, technical, and organizational safeguards, but no internet service can guarantee absolute security."] }, { title: "Children and changes", paragraphs: ["Our service is not directed to children under 13. We may update this policy from time to time and will post the revised version on this page with a new update date."] }]} /></main><Footer site={site} /><Chatbot /></div>;
}